name: Docker Build and Push

on:
  push:
    branches: [ master ]

jobs:
  build-and-push:
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install docker
        run: brew install docker

      - name: Build Docker image
        run: docker build --tag dchou1618/pyeng:latest --file Dockerfile .

      - name: Authenticate with Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to Docker Hub
        run: docker push dchou1618/pyeng:latest

